/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package xmltotxt;

import static java.io.FileDescriptor.in;
import static java.lang.System.in;
import java.util.ArrayList;
import java.util.Arrays;
import static sun.nio.cs.Surrogate.is;

/**
 *
 * @author syaban
 */
public class StopwordsRemoval {

    String[] Daftar = new String[10];
    private int token;
    private int tokenafterremove;
    String[] kata = null;
    String[] sw = null;
    public ArrayList<String> wordsList = new ArrayList<String>();

    public void setDaftar(String p, int i) {
        this.Daftar[i] = p;
//        Daftar[0]="Argentine bonds were slightly higher in a small technical bounce Wednesday amid low volume";
//        Daftar[1]="A trader at a large foreign bank said there was a slight technical bounce at the opening, and he did not expect prices to change much during the session as no market-moving news is expected";
//        Daftar[2]="The 5.5 percent dollar-denominated Bocon Previsional 2 due 2001 rose $0.15 to 115.15. Argentina's FRB due 2005 rose 1/8 to 77-3/8";
//        Daftar[3]="There is general uncertainty,\" said the trader, pointing to all the events the market is waiting for, including the passage of the government's new economic measures through Congress, which is now not expected until early October";
//        Daftar[4]="In addition, traders are awaiting a meeting Friday between Economy Minister Roque Fernandez and an International Monetary Fund delegation on Argentina's fiscal deficit";
    }

    public void doStopwordsRemoval() {
        String l = "";
        int tokenKeI = 0;
        String bufferOperand;
        String bufferKeyword = null;
        boolean cekNumber = false;
//    String[] token = new String[100];
        ArrayList<String> token = new ArrayList<String>();
        char var;
        String lama = null;
        String baru = null;
        
        for (int x = 0; x < 5; x++) {
            lama = lama + " " + Daftar[x];
        }
        lama.toLowerCase();
        //Mengghapus semua tanda baca keculi angka.
        String replaceAll = lama.replaceAll("[\".]","");        
        kata = replaceAll.split("\\s");
        System.out.println("sebelum dihilangkan stop words : ");
        for (int y = 1; y < kata.length; y++) {
            this.token = y;
        }
        
        //Menghilangkan stopword,angka dan tanda baca
        String replaceAll2 = lama.replaceAll("[\".,'/$1234567890-]"," ");        
        sw = replaceAll2.split("\\s");
        
        for (String word : sw) {
            wordsList.add(word);
        }

        for (int m = 0; m < wordsList.size(); m++) {
            // get the item as string
            for (int j = 0; j < stopWordsofwordnet.length; j++) {
                if (stopWordsofwordnet[j].contains(wordsList.get(m).toLowerCase())) {
                    wordsList.remove(m);
                }
            }
        }
        System.out.println("setelah dihilangkan stopwords menjadi : ");
        for (int y = 1; y < wordsList.size(); y++) {
            System.out.println(+y + ". " + wordsList.get(y));
        }
        this.tokenafterremove=wordsList.size();
    }

    
    public static String[] stopWordsofwordnet = {
        "a",
        "as",
        "able",
        "about",
        "above",
        "according",
        "accordingly",
        "across",
        "actually",
        "after",
        "afterwards",
        "again",
        "against",
        "aint",
        "all",
        "allow",
        "allows",
        "almost",
        "alone",
        "along",
        "already",
        "also",
        "although",
        "always",
        "am",
        "among",
        "amongst",
        "an",
        "and",
        "another",
        "any",
        "anybody",
        "anyhow",
        "anyone",
        "anything",
        "anyway",
        "anyways",
        "anywhere",
        "apart",
        "appear",
        "appreciate",
        "appropriate",
        "are",
        "arent",
        "around",
        "as",
        "aside",
        "ask",
        "asking",
        "associated",
        "at",
        "available",
        "away",
        "awfully",
        "b",
        "be",
        "became",
        "because",
        "become",
        "becomes",
        "becoming",
        "been",
        "before",
        "beforehand",
        "behind",
        "being",
        "believe",
        "below",
        "beside",
        "besides",
        "best",
        "better",
        "between",
        "beyond",
        "both",
        "brief",
        "but",
        "by",
        "c",
        "cmon",
        "cs",
        "came",
        "can",
        "cant",
        "cannot",
        "cant",
        "cause",
        "causes",
        "certain",
        "certainly",
        "changes",
        "clearly",
        "co",
        "com",
        "come",
        "comes",
        "concerning",
        "consequently",
        "consider",
        "considering",
        "contain",
        "containing",
        "contains",
        "corresponding",
        "could",
        "couldnt",
        "course",
        "currently",
        "d",
        "definitely",
        "described",
        "despite",
        "did",
        "didnt",
        "different",
        "do",
        "does",
        "doesnt",
        "doing",
        "dont",
        "done",
        "down",
        "downwards",
        "during",
        "e",
        "each",
        "edu",
        "eg",
        "eight",
        "either",
        "else",
        "elsewhere",
        "enough",
        "entirely",
        "especially",
        "et",
        "etc",
        "even",
        "ever",
        "every",
        "everybody",
        "everyone",
        "everything",
        "everywhere",
        "ex",
        "exactly",
        "example",
        "except",
        "f",
        "far",
        "few",
        "fifth",
        "first",
        "five",
        "followed",
        "following",
        "follows",
        "for",
        "former",
        "formerly",
        "forth",
        "four",
        "from",
        "further",
        "furthermore",
        "g",
        "get",
        "gets",
        "getting",
        "given",
        "gives",
        "go",
        "goes",
        "going",
        "gone",
        "got",
        "gotten",
        "greetings",
        "h",
        "had",
        "hadnt",
        "happens",
        "hardly",
        "has",
        "hasnt",
        "have",
        "havent",
        "having",
        "he",
        "hes",
        "hello",
        "help",
        "hence",
        "her",
        "here",
        "heres",
        "hereafter",
        "hereby",
        "herein",
        "hereupon",
        "hers",
        "herself",
        "hi",
        "him",
        "himself",
        "his",
        "hither",
        "hopefully",
        "how",
        "howbeit",
        "however",
        "i",
        "id",
        "ill",
        "im",
        "ive",
        "ie",
        "if",
        "ignored",
        "immediate",
        "in",
        "inasmuch",
        "inc",
        "indeed",
        "indicate",
        "indicated",
        "indicates",
        "inner",
        "insofar",
        "instead",
        "into",
        "inward",
        "is",
        "isnt",
        "it",
        "itd",
        "itll",
        "its",
        "its",
        "itself",
        "j",
        "just",
        "k",
        "keep",
        "keeps",
        "kept",
        "know",
        "knows",
        "known",
        "l",
        "last",
        "lately",
        "later",
        "latter",
        "latterly",
        "least",
        "less",
        "lest",
        "let",
        "lets",
        "like",
        "liked",
        "likely",
        "little",
        "look",
        "looking",
        "looks",
        "ltd",
        "m",
        "mainly",
        "many",
        "may",
        "maybe",
        "me",
        "mean",
        "meanwhile",
        "merely",
        "might",
        "more",
        "moreover",
        "most",
        "mostly",
        "much",
        "must",
        "my",
        "myself",
        "n",
        "name",
        "namely",
        "nd",
        "near",
        "nearly",
        "necessary",
        "need",
        "needs",
        "neither",
        "never",
        "nevertheless",
        "new",
        "next",
        "nine",
        "no",
        "nobody",
        "non",
        "none",
        "noone",
        "nor",
        "normally",
        "not",
        "nothing",
        "novel",
        "now",
        "nowhere",
        "o",
        "obviously",
        "of",
        "off",
        "often",
        "oh",
        "ok",
        "okay",
        "old",
        "on",
        "once",
        "one",
        "ones",
        "only",
        "onto",
        "or",
        "other",
        "others",
        "otherwise",
        "ought",
        "our",
        "ours",
        "ourselves",
        "out",
        "outside",
        "over",
        "overall",
        "own",
        "p",
        "particular",
        "particularly",
        "per",
        "perhaps",
        "placed",
        "please",
        "plus",
        "possible",
        "presumably",
        "probably",
        "provides",
        "q",
        "que",
        "quite",
        "qv",
        "r",
        "rather",
        "rd",
        "re",
        "really",
        "reasonably",
        "regarding",
        "regardless",
        "regards",
        "relatively",
        "respectively",
        "right",
        "s",
        "said",
        "same",
        "saw",
        "say",
        "saying",
        "says",
        "second",
        "secondly",
        "see",
        "seeing",
        "seem",
        "seemed",
        "seeming",
        "seems",
        "seen",
        "self",
        "selves",
        "sensible",
        "sent",
        "serious",
        "seriously",
        "seven",
        "several",
        "shall",
        "she",
        "should",
        "shouldnt",
        "since",
        "six",
        "so",
        "some",
        "somebody",
        "somehow",
        "someone",
        "something",
        "sometime",
        "sometimes",
        "somewhat",
        "somewhere",
        "soon",
        "sorry",
        "specified",
        "specify",
        "specifying",
        "still",
        "sub",
        "such",
        "sup",
        "sure",
        "t",
        "ts",
        "take",
        "taken",
        "tell",
        "tends",
        "th",
        "than",
        "thank",
        "thanks",
        "thanx",
        "that",
        "thats",
        "thats",
        "the",
        "their",
        "theirs",
        "them",
        "themselves",
        "then",
        "thence",
        "there",
        "theres",
        "thereafter",
        "thereby",
        "therefore",
        "therein",
        "theres",
        "thereupon",
        "these",
        "they",
        "theyd",
        "theyll",
        "theyre",
        "theyve",
        "think",
        "third",
        "this",
        "thorough",
        "thoroughly",
        "those",
        "though",
        "three",
        "through",
        "throughout",
        "thru",
        "thus",
        "to",
        "together",
        "too",
        "took",
        "toward",
        "towards",
        "tried",
        "tries",
        "truly",
        "try",
        "trying",
        "twice",
        "two",
        "u",
        "un",
        "under",
        "unfortunately",
        "unless",
        "unlikely",
        "until",
        "unto",
        "up",
        "upon",
        "us",
        "use",
        "used",
        "useful",
        "uses",
        "using",
        "usually",
        "uucp",
        "v",
        "value",
        "various",
        "very",
        "via",
        "viz",
        "vs",
        "w",
        "want",
        "wants",
        "was",
        "wasnt",
        "way",
        "we",
        "wed",
        "well",
        "were",
        "weve",
        "welcome",
        "well",
        "went",
        "were",
        "werent",
        "what",
        "whats",
        "whatever",
        "when",
        "whence",
        "whenever",
        "where",
        "wheres",
        "whereafter",
        "whereas",
        "whereby",
        "wherein",
        "whereupon",
        "wherever",
        "whether",
        "which",
        "while",
        "whither",
        "who",
        "whos",
        "whoever",
        "whole",
        "whom",
        "whose",
        "why",
        "will",
        "willing",
        "wish",
        "with",
        "within",
        "without",
        "wont",
        "wonder",
        "would",
        "would",
        "wouldnt",
        "x",
        "y",
        "yes",
        "yet",
        "you",
        "youd",
        "youll",
        "youre",
        "youve",
        "your",
        "yours",
        "yourself",
        "yourselves",
        "z",
        "zero"
    };

    /**
     * @return the token
     */
    public int getToken() {
        return token;
    }

    /**
     * @return the tokenafterremove
     */
    public int getTokenafterremove() {
        return tokenafterremove;
    }
}
